project_id = "zmewfhnaycjuvpjxkiin"

[functions.telegram-channel]
verify_jwt = true

[functions.create-robokassa-payment]
verify_jwt = false

[functions.robokassa-webhook]
verify_jwt = false

[functions.process-recurring-payments]
verify_jwt = true

[functions.notify-upcoming-payments]
verify_jwt = true

[functions.check-expired-subscriptions]
verify_jwt = true

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.get-subscriber-status]
verify_jwt = false

[functions.subscriber-status-change]
verify_jwt = true

[functions.cleanup-expired-invites]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = false
