project_id = "zmewfhnaycjuvpjxkiin"

[functions.telegram-channel]
verify_jwt = false

[functions.set-telegram-webhook]
verify_jwt = false

[functions.get-payment-history]
verify_jwt = false

[functions.create-robokassa-payment]
verify_jwt = false

[functions.robokassa-webhook]
verify_jwt = false

[functions.process-recurring-payments]
verify_jwt = true

[functions.notify-upcoming-payments]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.get-subscriber-status]
verify_jwt = false

[functions.subscriber-status-change]
verify_jwt = true

[functions.cleanup-expired-invites]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = false

[functions.notify-expiring-single-subscriptions]
verify_jwt = false

[functions.send-custom-telegram-message]
verify_jwt = false

[functions.get-public-app-config]
verify_jwt = false

[functions.get-public-tiers]
verify_jwt = false
